const workoutNames = [
  "Ball Crusher",
  "Whipped Cream",
  "Cake Cake Cake",
  "Thor",
  "Heaven & Hell",
  "Gold", "Silver",
  "Cannonball",
  "Hulk",
  "Star Lord",
  "White Walker",
  "Call of Duty",
  "Spellbound",
  "Sinister",
  "Villain",
  "Hera",
  "Hero",
  "Fallen",
  "Zeus",
  "Fight",
  "Guts & Glory",
  "Hot Shot",
  "Suzie Q",
  "Young Gun",
  "Epic",
  "Prom Queen",
  "Spartacus",
  "Tank",
  "The Crippler",
  "The Punisher",
  "Fancy Pants",
  "License To Kill",
  "Liquid Lifeforce",
  "Cult Sans Canon",
  "Cutlas Killers",
  "Demolition Demons",
  "Blood Circle",
  "Blood Rich",
  "Sins of Salem",
  "Souls of Salem",
  "Embers Rising",
  "Embers to Ashes",
"Embers of the Innocent",
"Death by Dogma",
"Scale of Osiris",
"Coccoon",
"Talisman",
"Instinct",
"Metamorphosis",
"Headhunters",
"Retain Terrain",
"Divided We Fall",
"Armored Army",
"Lost Legion",
"A House Divided",
"Echos of a Lost Age",
"Our Fathers War",
"Mutable Monsters",
"Assassins Alliance",
"Forsake the Fallen",
"Alchemic Elixer",
"Alchemy Assault",
"Shapeshifters",
"Live to Kill",
"Blood Loss",
"Bloodlust",
"Genocidal Tendencies",
"An Ancient Score",
"Vendetta to Victory",
"Eat What You Kill",
"Gaias Stewards",
"Tears of Gaia",
"Children of Gaia",
"Battle Cry",
"Mercy Mauling",
"Executor",
"Beg For Mercy",
"Deaf Executioners",
"The Merciful",
"Survival Strategy",
"Fungal Expansion",
"Unite the Clans",
"Sutures for the Future",
"Crescent Blow",
"Song of the Blade",
"Ringing Blades",
"Blades of Rage",
"Hippocrates Bane",
"Line of Sight",
"Systems of Survival",
"Diplomacy of the Sword",
"Marauding Maces",
"Defaced by Mace",
"Written in Blood",
"Blood Oath",
"Iron Edge",
"By the Sword",
"Leathernecks",
"Skin Peels",
"Death by Boomstick",
"Ragtag Rush",
"Rippers",
"Insect Autopsy",
"Viking Vivisection",
"Ne Agito Oppet",
"Cotton Candy",
"Rainbow Sprinkles",
"Vanilla",
"Ice Cream",
"Sundae",
]

export { workoutNames }
